import type { PoiDisplayMetadata } from '@/constants/osm-mapping.ts'

// Values from the OpenMapTiles POI layer mapping in poi/mapping.yaml, plus SQL-derived values.
export enum OmtPoiSubclass {
  Accessories = 'accessories',
  Accountant = 'accountant',
  AdvertisingAgency = 'advertising_agency',
  Alcohol = 'alcohol',
  AlpineHut = 'alpine_hut',
  AmericanFootball = 'american_football',
  Antiques = 'antiques',
  Aquarium = 'aquarium',
  Archery = 'archery',
  Architect = 'architect',
  Art = 'art',
  ArtsCentre = 'arts_centre',
  Artwork = 'artwork',
  Association = 'association',
  Athletics = 'athletics',
  Atm = 'atm',
  Attraction = 'attraction',
  AustralianFootball = 'australian_football',
  Aviary = 'aviary',
  Badminton = 'badminton',
  Bag = 'bag',
  BailBondAgent = 'bail_bond_agent',
  Bakery = 'bakery',
  Bank = 'bank',
  Bar = 'bar',
  Baseball = 'baseball',
  Basin = 'basin',
  Basketball = 'basketball',
  Bbq = 'bbq',
  Beachvolleyball = 'beachvolleyball',
  Beauty = 'beauty',
  Bed = 'bed',
  BedAndBreakfast = 'bed_and_breakfast',
  Beverages = 'beverages',
  Bicycle = 'bicycle',
  BicycleParking = 'bicycle_parking',
  BicycleRental = 'bicycle_rental',
  Biergarten = 'biergarten',
  Billiards = 'billiards',
  Birds = 'birds',
  Bmx = 'bmx',
  Bollard = 'bollard',
  Books = 'books',
  BorderControl = 'border_control',
  Boules = 'boules',
  Boutique = 'boutique',
  Bowls = 'bowls',
  Boxing = 'boxing',
  Brownfield = 'brownfield',
  BusStation = 'bus_station',
  BusStop = 'bus_stop',
  Butcher = 'butcher',
  Butterfly = 'butterfly',
  Cafe = 'cafe',
  Camera = 'camera',
  CampSite = 'camp_site',
  CanadianFootball = 'canadian_football',
  Canoe = 'canoe',
  Car = 'car',
  CarParts = 'car_parts',
  CarRepair = 'car_repair',
  CaravanSite = 'caravan_site',
  Carpet = 'carpet',
  Castle = 'castle',
  Cemetery = 'cemetery',
  Chalet = 'chalet',
  ChargingStation = 'charging_station',
  Charity = 'charity',
  Chemist = 'chemist',
  Chess = 'chess',
  Chocolate = 'chocolate',
  Cinema = 'cinema',
  Climbing = 'climbing',
  ClimbingAdventure = 'climbing_adventure',
  Clinic = 'clinic',
  Clothes = 'clothes',
  Coffee = 'coffee',
  College = 'college',
  CommunityCentre = 'community_centre',
  Company = 'company',
  Computer = 'computer',
  Confectionery = 'confectionery',
  ConstructionCompany = 'construction_company',
  Consulting = 'consulting',
  Convenience = 'convenience',
  Cooperative = 'cooperative',
  Copyshop = 'copyshop',
  Cosmetics = 'cosmetics',
  Courier = 'courier',
  Courthouse = 'courthouse',
  Coworking = 'coworking',
  Cricket = 'cricket',
  CricketNets = 'cricket_nets',
  Croquet = 'croquet',
  Curling = 'curling',
  CycleBarrier = 'cycle_barrier',
  Cycling = 'cycling',
  Deli = 'deli',
  Delicatessen = 'delicatessen',
  Dentist = 'dentist',
  DepartmentStore = 'department_store',
  Diplomatic = 'diplomatic',
  DiscGolf = 'disc_golf',
  Diving = 'diving',
  Dock = 'dock',
  Doctors = 'doctors',
  DogPark = 'dog_park',
  DogRacing = 'dog_racing',
  Doityourself = 'doityourself',
  Dormitory = 'dormitory',
  DrinkingWater = 'drinking_water',
  DryCleaning = 'dry_cleaning',
  EducationalInstitution = 'educational_institution',
  Electronics = 'electronics',
  EmploymentAgency = 'employment_agency',
  Enclosure = 'enclosure',
  EnergySupplier = 'energy_supplier',
  Engineer = 'engineer',
  Equestrian = 'equestrian',
  Erotic = 'erotic',
  EscapeGame = 'escape_game',
  EstateAgent = 'estate_agent',
  Fabric = 'fabric',
  Falconry = 'falconry',
  FastFood = 'fast_food',
  Fatsal = 'fatsal',
  FerryTerminal = 'ferry_terminal',
  FieldHockey = 'field_hockey',
  Financial = 'financial',
  FinancialAdvisor = 'financial_advisor',
  FireStation = 'fire_station',
  Florist = 'florist',
  FoodCourt = 'food_court',
  Forestry = 'forestry',
  Foundation = 'foundation',
  FreeFlying = 'free_flying',
  FrozenFood = 'frozen_food',
  Fuel = 'fuel',
  Furniture = 'furniture',
  GaelicGames = 'gaelic_games',
  Gallery = 'gallery',
  Garden = 'garden',
  GardenCentre = 'garden_centre',
  Gate = 'gate',
  General = 'general',
  Geodesist = 'geodesist',
  Gift = 'gift',
  Golf = 'golf',
  GolfCourse = 'golf_course',
  Government = 'government',
  GraphicDesign = 'graphic_design',
  GraveYard = 'grave_yard',
  Greengrocer = 'greengrocer',
  GuestHouse = 'guest_house',
  Guide = 'guide',
  Gymnastics = 'gymnastics',
  Hackerspace = 'hackerspace',
  Hairdresser = 'hairdresser',
  Halt = 'halt',
  Handball = 'handball',
  HarbourMaster = 'harbour_master',
  Hardware = 'hardware',
  HealthInsurance = 'health_insurance',
  HearingAids = 'hearing_aids',
  Hifi = 'hifi',
  Hockey = 'hockey',
  HorseRacing = 'horse_racing',
  Horseshoes = 'horseshoes',
  Hospital = 'hospital',
  Hostel = 'hostel',
  Hotel = 'hotel',
  IceCream = 'ice_cream',
  IceHockey = 'ice_hockey',
  IceRink = 'ice_rink',
  IceStock = 'ice_stock',
  Information = 'information',
  Insurance = 'insurance',
  InteriorDecoration = 'interior_decoration',
  InteriorDesign = 'interior_design',
  It = 'it',
  Jewelry = 'jewelry',
  Judo = 'judo',
  Karting = 'karting',
  Kindergarten = 'kindergarten',
  Kiosk = 'kiosk',
  Korfball = 'korfball',
  Lamps = 'lamps',
  Laundry = 'laundry',
  Lawyer = 'lawyer',
  Library = 'library',
  LiftGate = 'lift_gate',
  Locksmith = 'locksmith',
  Logistics = 'logistics',
  LongJump = 'long_jump',
  Mall = 'mall',
  Marina = 'marina',
  Marketing = 'marketing',
  Marketplace = 'marketplace',
  Massage = 'massage',
  MiniatureGolf = 'miniature_golf',
  MobilePhone = 'mobile_phone',
  ModelAerodrome = 'model_aerodrome',
  Monument = 'monument',
  Motel = 'motel',
  Motocross = 'motocross',
  Motor = 'motor',
  Motorcycle = 'motorcycle',
  MotorcycleParking = 'motorcycle_parking',
  MovingCompany = 'moving_company',
  Multi = 'multi',
  Museum = 'museum',
  Music = 'music',
  MusicalInstrument = 'musical_instrument',
  Netball = 'netball',
  Newsagent = 'newsagent',
  Newspaper = 'newspaper',
  Ngo = 'ngo',
  Nightclub = 'nightclub',
  Notary = 'notary',
  NursingHome = 'nursing_home',
  Optician = 'optician',
  Orienteering = 'orienteering',
  Outdoor = 'outdoor',
  PaddleTennis = 'paddle_tennis',
  Paint = 'paint',
  Paintball = 'paintball',
  Paragliding = 'paragliding',
  ParcelLocker = 'parcel_locker',
  Park = 'park',
  Parking = 'parking',
  Pelota = 'pelota',
  Perfume = 'perfume',
  Perfumery = 'perfumery',
  Pet = 'pet',
  PettingZoo = 'petting_zoo',
  Pharmacy = 'pharmacy',
  Photo = 'photo',
  Physician = 'physician',
  PicnicSite = 'picnic_site',
  Pitch = 'pitch',
  PlaceOfWorship = 'place_of_worship',
  Playground = 'playground',
  Police = 'police',
  PoliticalParty = 'political_party',
  PostBox = 'post_box',
  PostOffice = 'post_office',
  Prison = 'prison',
  PrivateInvestigator = 'private_investigator',
  PropertyManagement = 'property_management',
  Pub = 'pub',
  PublicBuilding = 'public_building',
  Publisher = 'publisher',
  Quango = 'quango',
  Racquet = 'racquet',
  RcCar = 'rc_car',
  Recycling = 'recycling',
  Religion = 'religion',
  Reptile = 'reptile',
  Research = 'research',
  Reservoir = 'reservoir',
  Restaurant = 'restaurant',
  Rowing = 'rowing',
  Rugby = 'rugby',
  RugbyLeague = 'rugby_league',
  RugbyUnion = 'rugby_union',
  Ruins = 'ruins',
  Running = 'running',
  SafariPark = 'safari_park',
  Sailing = 'sailing',
  SallyPort = 'sally_port',
  School = 'school',
  ScubaDiving = 'scuba_diving',
  SecondHand = 'second_hand',
  Security = 'security',
  Shelter = 'shelter',
  Shoes = 'shoes',
  Shooting = 'shooting',
  ShootingRange = 'shooting_range',
  Skateboard = 'skateboard',
  Skating = 'skating',
  Skiing = 'skiing',
  Soccer = 'soccer',
  Sports = 'sports',
  SportsCentre = 'sports_centre',
  Stadium = 'stadium',
  Station = 'station',
  Stationery = 'stationery',
  Stile = 'stile',
  Subway = 'subway',
  SubwayEntrance = 'subway_entrance',
  Supermarket = 'supermarket',
  Surfing = 'surfing',
  Surveyor = 'surveyor',
  Swimming = 'swimming',
  SwimmingArea = 'swimming_area',
  SwimmingPool = 'swimming_pool',
  TableSoccer = 'table_soccer',
  TableTennis = 'table_tennis',
  Tailor = 'tailor',
  Tattoo = 'tattoo',
  TaxAdvisor = 'tax_advisor',
  Taxi = 'taxi',
  TeamHandball = 'team_handball',
  Telecommunication = 'telecommunication',
  Telephone = 'telephone',
  Tennis = 'tennis',
  Terrarium = 'terrarium',
  Theatre = 'theatre',
  ThemePark = 'theme_park',
  Therapist = 'therapist',
  Ticket = 'ticket',
  Tobacco = 'tobacco',
  Toboggan = 'toboggan',
  Toilets = 'toilets',
  TollBooth = 'toll_booth',
  Townhall = 'townhall',
  Toys = 'toys',
  TrainStationEntrance = 'train_station_entrance',
  TramStop = 'tram_stop',
  Translator = 'translator',
  TravelAgency = 'travel_agency',
  TravelAgent = 'travel_agent',
  Tutoring = 'tutoring',
  Union = 'union',
  University = 'university',
  Veterinary = 'veterinary',
  Video = 'video',
  VideoGames = 'video_games',
  Viewpoint = 'viewpoint',
  Volleyball = 'volleyball',
  WasteBasket = 'waste_basket',
  Watches = 'watches',
  WaterPark = 'water_park',
  WaterSki = 'water_ski',
  WaterUtility = 'water_utility',
  Weapons = 'weapons',
  WebDesign = 'web_design',
  WeddingPlanner = 'wedding_planner',
  Wholesale = 'wholesale',
  WildlifePark = 'wildlife_park',
  Wine = 'wine',
  WinterSports = 'winter_sports',
  Yoga = 'yoga',
  Zoo = 'zoo',
}

const OMT_POI_SUBCLASS_ICONS: Record<OmtPoiSubclass, string> = {
  [OmtPoiSubclass.Accessories]: 'lucide:shopping-bag',
  [OmtPoiSubclass.Accountant]: 'lucide:landmark',
  [OmtPoiSubclass.AdvertisingAgency]: 'lucide:megaphone',
  [OmtPoiSubclass.Alcohol]: 'lucide:beer',
  [OmtPoiSubclass.AlpineHut]: 'lucide:mountain',
  [OmtPoiSubclass.AmericanFootball]: 'lucide:trophy',
  [OmtPoiSubclass.Antiques]: 'lucide:store',
  [OmtPoiSubclass.Aquarium]: 'lucide:waves',
  [OmtPoiSubclass.Archery]: 'lucide:target',
  [OmtPoiSubclass.Architect]: 'lucide:ruler',
  [OmtPoiSubclass.Art]: 'lucide:palette',
  [OmtPoiSubclass.ArtsCentre]: 'lucide:palette',
  [OmtPoiSubclass.Artwork]: 'lucide:palette',
  [OmtPoiSubclass.Association]: 'lucide:users',
  [OmtPoiSubclass.Athletics]: 'lucide:trophy',
  [OmtPoiSubclass.Atm]: 'lucide:banknote',
  [OmtPoiSubclass.Attraction]: 'lucide:star',
  [OmtPoiSubclass.AustralianFootball]: 'lucide:trophy',
  [OmtPoiSubclass.Aviary]: 'lucide:bird',
  [OmtPoiSubclass.Badminton]: 'lucide:trophy',
  [OmtPoiSubclass.Bag]: 'lucide:shopping-bag',
  [OmtPoiSubclass.BailBondAgent]: 'lucide:landmark',
  [OmtPoiSubclass.Bakery]: 'lucide:wheat',
  [OmtPoiSubclass.Bank]: 'lucide:landmark',
  [OmtPoiSubclass.Bar]: 'lucide:beer',
  [OmtPoiSubclass.Baseball]: 'lucide:trophy',
  [OmtPoiSubclass.Basin]: 'lucide:map-pin',
  [OmtPoiSubclass.Basketball]: 'lucide:trophy',
  [OmtPoiSubclass.Bbq]: 'lucide:flame-kindling',
  [OmtPoiSubclass.Beachvolleyball]: 'lucide:trophy',
  [OmtPoiSubclass.Beauty]: 'lucide:sparkles',
  [OmtPoiSubclass.Bed]: 'lucide:bed',
  [OmtPoiSubclass.BedAndBreakfast]: 'lucide:bed',
  [OmtPoiSubclass.Beverages]: 'lucide:wine',
  [OmtPoiSubclass.Bicycle]: 'lucide:bike',
  [OmtPoiSubclass.BicycleParking]: 'lucide:bike',
  [OmtPoiSubclass.BicycleRental]: 'lucide:bike',
  [OmtPoiSubclass.Biergarten]: 'lucide:beer',
  [OmtPoiSubclass.Billiards]: 'lucide:trophy',
  [OmtPoiSubclass.Birds]: 'lucide:bird',
  [OmtPoiSubclass.Bmx]: 'lucide:bike',
  [OmtPoiSubclass.Bollard]: 'lucide:circle-slash',
  [OmtPoiSubclass.Books]: 'lucide:book-open',
  [OmtPoiSubclass.BorderControl]: 'lucide:shield',
  [OmtPoiSubclass.Boules]: 'lucide:trophy',
  [OmtPoiSubclass.Boutique]: 'lucide:shirt',
  [OmtPoiSubclass.Bowls]: 'lucide:trophy',
  [OmtPoiSubclass.Boxing]: 'lucide:trophy',
  [OmtPoiSubclass.Brownfield]: 'lucide:factory',
  [OmtPoiSubclass.BusStation]: 'lucide:bus',
  [OmtPoiSubclass.BusStop]: 'lucide:bus',
  [OmtPoiSubclass.Butcher]: 'lucide:store',
  [OmtPoiSubclass.Butterfly]: 'lucide:bug',
  [OmtPoiSubclass.Cafe]: 'lucide:coffee',
  [OmtPoiSubclass.Camera]: 'lucide:camera',
  [OmtPoiSubclass.CampSite]: 'lucide:tent',
  [OmtPoiSubclass.CanadianFootball]: 'lucide:trophy',
  [OmtPoiSubclass.Canoe]: 'lucide:ship',
  [OmtPoiSubclass.Car]: 'lucide:car',
  [OmtPoiSubclass.CarParts]: 'lucide:car',
  [OmtPoiSubclass.CarRepair]: 'lucide:wrench',
  [OmtPoiSubclass.CaravanSite]: 'lucide:caravan',
  [OmtPoiSubclass.Carpet]: 'lucide:store',
  [OmtPoiSubclass.Castle]: 'lucide:castle',
  [OmtPoiSubclass.Cemetery]: 'lucide:landmark',
  [OmtPoiSubclass.Chalet]: 'lucide:house',
  [OmtPoiSubclass.ChargingStation]: 'lucide:battery-charging',
  [OmtPoiSubclass.Charity]: 'lucide:heart-handshake',
  [OmtPoiSubclass.Chemist]: 'lucide:pill',
  [OmtPoiSubclass.Chess]: 'lucide:trophy',
  [OmtPoiSubclass.Chocolate]: 'lucide:candy',
  [OmtPoiSubclass.Cinema]: 'lucide:film',
  [OmtPoiSubclass.Climbing]: 'lucide:mountain',
  [OmtPoiSubclass.ClimbingAdventure]: 'lucide:mountain',
  [OmtPoiSubclass.Clinic]: 'lucide:cross',
  [OmtPoiSubclass.Clothes]: 'lucide:shirt',
  [OmtPoiSubclass.Coffee]: 'lucide:coffee',
  [OmtPoiSubclass.College]: 'lucide:graduation-cap',
  [OmtPoiSubclass.CommunityCentre]: 'lucide:building-2',
  [OmtPoiSubclass.Company]: 'lucide:briefcase-business',
  [OmtPoiSubclass.Computer]: 'lucide:monitor',
  [OmtPoiSubclass.Confectionery]: 'lucide:candy',
  [OmtPoiSubclass.ConstructionCompany]: 'lucide:hard-hat',
  [OmtPoiSubclass.Consulting]: 'lucide:briefcase-business',
  [OmtPoiSubclass.Convenience]: 'lucide:store',
  [OmtPoiSubclass.Cooperative]: 'lucide:users',
  [OmtPoiSubclass.Copyshop]: 'lucide:printer',
  [OmtPoiSubclass.Cosmetics]: 'lucide:sparkles',
  [OmtPoiSubclass.Courier]: 'lucide:package',
  [OmtPoiSubclass.Courthouse]: 'lucide:scale',
  [OmtPoiSubclass.Coworking]: 'lucide:briefcase-business',
  [OmtPoiSubclass.Cricket]: 'lucide:trophy',
  [OmtPoiSubclass.CricketNets]: 'lucide:trophy',
  [OmtPoiSubclass.Croquet]: 'lucide:trophy',
  [OmtPoiSubclass.Curling]: 'lucide:trophy',
  [OmtPoiSubclass.CycleBarrier]: 'lucide:bike',
  [OmtPoiSubclass.Cycling]: 'lucide:bike',
  [OmtPoiSubclass.Deli]: 'lucide:utensils',
  [OmtPoiSubclass.Delicatessen]: 'lucide:utensils',
  [OmtPoiSubclass.Dentist]: 'lucide:cross',
  [OmtPoiSubclass.DepartmentStore]: 'lucide:store',
  [OmtPoiSubclass.Diplomatic]: 'lucide:landmark',
  [OmtPoiSubclass.DiscGolf]: 'lucide:flag',
  [OmtPoiSubclass.Diving]: 'lucide:waves',
  [OmtPoiSubclass.Dock]: 'lucide:ship',
  [OmtPoiSubclass.Doctors]: 'lucide:stethoscope',
  [OmtPoiSubclass.DogPark]: 'lucide:paw-print',
  [OmtPoiSubclass.DogRacing]: 'lucide:paw-print',
  [OmtPoiSubclass.Doityourself]: 'lucide:hammer',
  [OmtPoiSubclass.Dormitory]: 'lucide:bed',
  [OmtPoiSubclass.DrinkingWater]: 'lucide:droplets',
  [OmtPoiSubclass.DryCleaning]: 'lucide:washing-machine',
  [OmtPoiSubclass.EducationalInstitution]: 'lucide:graduation-cap',
  [OmtPoiSubclass.Electronics]: 'lucide:plug',
  [OmtPoiSubclass.EmploymentAgency]: 'lucide:briefcase-business',
  [OmtPoiSubclass.Enclosure]: 'lucide:paw-print',
  [OmtPoiSubclass.EnergySupplier]: 'lucide:zap',
  [OmtPoiSubclass.Engineer]: 'lucide:wrench',
  [OmtPoiSubclass.Equestrian]: 'lucide:trophy',
  [OmtPoiSubclass.Erotic]: 'lucide:store',
  [OmtPoiSubclass.EscapeGame]: 'lucide:puzzle',
  [OmtPoiSubclass.EstateAgent]: 'lucide:house',
  [OmtPoiSubclass.Fabric]: 'lucide:shirt',
  [OmtPoiSubclass.Falconry]: 'lucide:bird',
  [OmtPoiSubclass.FastFood]: 'lucide:hamburger',
  [OmtPoiSubclass.Fatsal]: 'lucide:trophy',
  [OmtPoiSubclass.FerryTerminal]: 'lucide:ship',
  [OmtPoiSubclass.FieldHockey]: 'lucide:trophy',
  [OmtPoiSubclass.Financial]: 'lucide:landmark',
  [OmtPoiSubclass.FinancialAdvisor]: 'lucide:landmark',
  [OmtPoiSubclass.FireStation]: 'lucide:flame',
  [OmtPoiSubclass.Florist]: 'lucide:flower-2',
  [OmtPoiSubclass.FoodCourt]: 'lucide:utensils',
  [OmtPoiSubclass.Forestry]: 'lucide:trees',
  [OmtPoiSubclass.Foundation]: 'lucide:building-2',
  [OmtPoiSubclass.FreeFlying]: 'lucide:plane',
  [OmtPoiSubclass.FrozenFood]: 'lucide:snowflake',
  [OmtPoiSubclass.Fuel]: 'lucide:fuel',
  [OmtPoiSubclass.Furniture]: 'lucide:armchair',
  [OmtPoiSubclass.GaelicGames]: 'lucide:trophy',
  [OmtPoiSubclass.Gallery]: 'lucide:images',
  [OmtPoiSubclass.Garden]: 'lucide:flower-2',
  [OmtPoiSubclass.GardenCentre]: 'lucide:flower-2',
  [OmtPoiSubclass.Gate]: 'lucide:door-open',
  [OmtPoiSubclass.General]: 'lucide:store',
  [OmtPoiSubclass.Geodesist]: 'lucide:ruler',
  [OmtPoiSubclass.Gift]: 'lucide:gift',
  [OmtPoiSubclass.Golf]: 'lucide:flag',
  [OmtPoiSubclass.GolfCourse]: 'lucide:flag',
  [OmtPoiSubclass.Government]: 'lucide:landmark',
  [OmtPoiSubclass.GraphicDesign]: 'lucide:palette',
  [OmtPoiSubclass.GraveYard]: 'lucide:landmark',
  [OmtPoiSubclass.Greengrocer]: 'lucide:shopping-basket',
  [OmtPoiSubclass.GuestHouse]: 'lucide:bed',
  [OmtPoiSubclass.Guide]: 'lucide:map',
  [OmtPoiSubclass.Gymnastics]: 'lucide:trophy',
  [OmtPoiSubclass.Hackerspace]: 'lucide:code-2',
  [OmtPoiSubclass.Hairdresser]: 'lucide:map-pin',
  [OmtPoiSubclass.Halt]: 'lucide:train-front',
  [OmtPoiSubclass.Handball]: 'lucide:trophy',
  [OmtPoiSubclass.HarbourMaster]: 'lucide:ship',
  [OmtPoiSubclass.Hardware]: 'lucide:hammer',
  [OmtPoiSubclass.HealthInsurance]: 'lucide:heart-pulse',
  [OmtPoiSubclass.HearingAids]: 'lucide:ear',
  [OmtPoiSubclass.Hifi]: 'lucide:audio-lines',
  [OmtPoiSubclass.Hockey]: 'lucide:trophy',
  [OmtPoiSubclass.HorseRacing]: 'lucide:trophy',
  [OmtPoiSubclass.Horseshoes]: 'lucide:trophy',
  [OmtPoiSubclass.Hospital]: 'lucide:hospital',
  [OmtPoiSubclass.Hostel]: 'lucide:bed',
  [OmtPoiSubclass.Hotel]: 'lucide:hotel',
  [OmtPoiSubclass.IceCream]: 'lucide:ice-cream-bowl',
  [OmtPoiSubclass.IceHockey]: 'lucide:trophy',
  [OmtPoiSubclass.IceRink]: 'lucide:snowflake',
  [OmtPoiSubclass.IceStock]: 'lucide:trophy',
  [OmtPoiSubclass.Information]: 'lucide:info',
  [OmtPoiSubclass.Insurance]: 'lucide:shield-check',
  [OmtPoiSubclass.InteriorDecoration]: 'lucide:paintbrush',
  [OmtPoiSubclass.InteriorDesign]: 'lucide:ruler',
  [OmtPoiSubclass.It]: 'lucide:monitor',
  [OmtPoiSubclass.Jewelry]: 'lucide:gem',
  [OmtPoiSubclass.Judo]: 'lucide:trophy',
  [OmtPoiSubclass.Karting]: 'lucide:car',
  [OmtPoiSubclass.Kindergarten]: 'lucide:baby',
  [OmtPoiSubclass.Kiosk]: 'lucide:store',
  [OmtPoiSubclass.Korfball]: 'lucide:trophy',
  [OmtPoiSubclass.Lamps]: 'lucide:lamp',
  [OmtPoiSubclass.Laundry]: 'lucide:washing-machine',
  [OmtPoiSubclass.Lawyer]: 'lucide:scale',
  [OmtPoiSubclass.Library]: 'lucide:book-open',
  [OmtPoiSubclass.LiftGate]: 'lucide:door-open',
  [OmtPoiSubclass.Locksmith]: 'lucide:key-round',
  [OmtPoiSubclass.Logistics]: 'lucide:truck',
  [OmtPoiSubclass.LongJump]: 'lucide:trophy',
  [OmtPoiSubclass.Mall]: 'lucide:store',
  [OmtPoiSubclass.Marina]: 'lucide:ship',
  [OmtPoiSubclass.Marketing]: 'lucide:megaphone',
  [OmtPoiSubclass.Marketplace]: 'lucide:store',
  [OmtPoiSubclass.Massage]: 'lucide:sparkles',
  [OmtPoiSubclass.MiniatureGolf]: 'lucide:flag',
  [OmtPoiSubclass.MobilePhone]: 'lucide:smartphone',
  [OmtPoiSubclass.ModelAerodrome]: 'lucide:plane',
  [OmtPoiSubclass.Monument]: 'lucide:landmark',
  [OmtPoiSubclass.Motel]: 'lucide:bed',
  [OmtPoiSubclass.Motocross]: 'lucide:bike',
  [OmtPoiSubclass.Motor]: 'lucide:car',
  [OmtPoiSubclass.Motorcycle]: 'lucide:bike',
  [OmtPoiSubclass.MotorcycleParking]: 'lucide:bike',
  [OmtPoiSubclass.MovingCompany]: 'lucide:truck',
  [OmtPoiSubclass.Multi]: 'lucide:trophy',
  [OmtPoiSubclass.Museum]: 'lucide:landmark',
  [OmtPoiSubclass.Music]: 'lucide:music',
  [OmtPoiSubclass.MusicalInstrument]: 'lucide:music',
  [OmtPoiSubclass.Netball]: 'lucide:trophy',
  [OmtPoiSubclass.Newsagent]: 'lucide:newspaper',
  [OmtPoiSubclass.Newspaper]: 'lucide:newspaper',
  [OmtPoiSubclass.Ngo]: 'lucide:users',
  [OmtPoiSubclass.Nightclub]: 'lucide:music',
  [OmtPoiSubclass.Notary]: 'lucide:scale',
  [OmtPoiSubclass.NursingHome]: 'lucide:heart-pulse',
  [OmtPoiSubclass.Optician]: 'lucide:glasses',
  [OmtPoiSubclass.Orienteering]: 'lucide:compass',
  [OmtPoiSubclass.Outdoor]: 'lucide:tent',
  [OmtPoiSubclass.PaddleTennis]: 'lucide:trophy',
  [OmtPoiSubclass.Paint]: 'lucide:paintbrush',
  [OmtPoiSubclass.Paintball]: 'lucide:trophy',
  [OmtPoiSubclass.Paragliding]: 'lucide:plane',
  [OmtPoiSubclass.ParcelLocker]: 'lucide:package',
  [OmtPoiSubclass.Park]: 'lucide:trees',
  [OmtPoiSubclass.Parking]: 'lucide:square-parking',
  [OmtPoiSubclass.Pelota]: 'lucide:trophy',
  [OmtPoiSubclass.Perfume]: 'lucide:sparkles',
  [OmtPoiSubclass.Perfumery]: 'lucide:sparkles',
  [OmtPoiSubclass.Pet]: 'lucide:paw-print',
  [OmtPoiSubclass.PettingZoo]: 'lucide:paw-print',
  [OmtPoiSubclass.Pharmacy]: 'lucide:pill',
  [OmtPoiSubclass.Photo]: 'lucide:camera',
  [OmtPoiSubclass.Physician]: 'lucide:stethoscope',
  [OmtPoiSubclass.PicnicSite]: 'lucide:tree-pine',
  [OmtPoiSubclass.Pitch]: 'lucide:trophy',
  [OmtPoiSubclass.PlaceOfWorship]: 'lucide:church',
  [OmtPoiSubclass.Playground]: 'lucide:gamepad-2',
  [OmtPoiSubclass.Police]: 'lucide:shield',
  [OmtPoiSubclass.PoliticalParty]: 'lucide:landmark',
  [OmtPoiSubclass.PostBox]: 'lucide:mailbox',
  [OmtPoiSubclass.PostOffice]: 'lucide:mail',
  [OmtPoiSubclass.Prison]: 'lucide:lock',
  [OmtPoiSubclass.PrivateInvestigator]: 'lucide:search',
  [OmtPoiSubclass.PropertyManagement]: 'lucide:house',
  [OmtPoiSubclass.Pub]: 'lucide:beer',
  [OmtPoiSubclass.PublicBuilding]: 'lucide:landmark',
  [OmtPoiSubclass.Publisher]: 'lucide:newspaper',
  [OmtPoiSubclass.Quango]: 'lucide:building-2',
  [OmtPoiSubclass.Racquet]: 'lucide:trophy',
  [OmtPoiSubclass.RcCar]: 'lucide:car',
  [OmtPoiSubclass.Recycling]: 'lucide:recycle',
  [OmtPoiSubclass.Religion]: 'lucide:church',
  [OmtPoiSubclass.Reptile]: 'lucide:paw-print',
  [OmtPoiSubclass.Research]: 'lucide:microscope',
  [OmtPoiSubclass.Reservoir]: 'lucide:waves',
  [OmtPoiSubclass.Restaurant]: 'lucide:map-pin',
  [OmtPoiSubclass.Rowing]: 'lucide:ship',
  [OmtPoiSubclass.Rugby]: 'lucide:trophy',
  [OmtPoiSubclass.RugbyLeague]: 'lucide:trophy',
  [OmtPoiSubclass.RugbyUnion]: 'lucide:trophy',
  [OmtPoiSubclass.Ruins]: 'lucide:landmark',
  [OmtPoiSubclass.Running]: 'lucide:footprints',
  [OmtPoiSubclass.SafariPark]: 'lucide:paw-print',
  [OmtPoiSubclass.Sailing]: 'lucide:ship',
  [OmtPoiSubclass.SallyPort]: 'lucide:door-open',
  [OmtPoiSubclass.School]: 'lucide:school',
  [OmtPoiSubclass.ScubaDiving]: 'lucide:waves',
  [OmtPoiSubclass.SecondHand]: 'lucide:refresh-cw',
  [OmtPoiSubclass.Security]: 'lucide:shield',
  [OmtPoiSubclass.Shelter]: 'lucide:tent',
  [OmtPoiSubclass.Shoes]: 'lucide:footprints',
  [OmtPoiSubclass.Shooting]: 'lucide:target',
  [OmtPoiSubclass.ShootingRange]: 'lucide:target',
  [OmtPoiSubclass.Skateboard]: 'lucide:trophy',
  [OmtPoiSubclass.Skating]: 'lucide:trophy',
  [OmtPoiSubclass.Skiing]: 'lucide:mountain-snow',
  [OmtPoiSubclass.Soccer]: 'lucide:circle',
  [OmtPoiSubclass.Sports]: 'lucide:dumbbell',
  [OmtPoiSubclass.SportsCentre]: 'lucide:dumbbell',
  [OmtPoiSubclass.Stadium]: 'lucide:trophy',
  [OmtPoiSubclass.Station]: 'lucide:train-front',
  [OmtPoiSubclass.Stationery]: 'lucide:notebook-pen',
  [OmtPoiSubclass.Stile]: 'lucide:door-open',
  [OmtPoiSubclass.Subway]: 'lucide:train-front',
  [OmtPoiSubclass.SubwayEntrance]: 'lucide:train-front',
  [OmtPoiSubclass.Supermarket]: 'lucide:shopping-cart',
  [OmtPoiSubclass.Surfing]: 'lucide:waves',
  [OmtPoiSubclass.Surveyor]: 'lucide:ruler',
  [OmtPoiSubclass.Swimming]: 'lucide:waves',
  [OmtPoiSubclass.SwimmingArea]: 'lucide:waves',
  [OmtPoiSubclass.SwimmingPool]: 'lucide:waves',
  [OmtPoiSubclass.TableSoccer]: 'lucide:trophy',
  [OmtPoiSubclass.TableTennis]: 'lucide:trophy',
  [OmtPoiSubclass.Tailor]: 'lucide:scissors',
  [OmtPoiSubclass.Tattoo]: 'lucide:paintbrush',
  [OmtPoiSubclass.TaxAdvisor]: 'lucide:landmark',
  [OmtPoiSubclass.Taxi]: 'lucide:car-taxi-front',
  [OmtPoiSubclass.TeamHandball]: 'lucide:trophy',
  [OmtPoiSubclass.Telecommunication]: 'lucide:radio-tower',
  [OmtPoiSubclass.Telephone]: 'lucide:phone',
  [OmtPoiSubclass.Tennis]: 'lucide:trophy',
  [OmtPoiSubclass.Terrarium]: 'lucide:paw-print',
  [OmtPoiSubclass.Theatre]: 'lucide:theater',
  [OmtPoiSubclass.ThemePark]: 'lucide:roller-coaster',
  [OmtPoiSubclass.Therapist]: 'lucide:heart-pulse',
  [OmtPoiSubclass.Ticket]: 'lucide:ticket',
  [OmtPoiSubclass.Tobacco]: 'lucide:cigarette',
  [OmtPoiSubclass.Toboggan]: 'lucide:mountain-snow',
  [OmtPoiSubclass.Toilets]: 'lucide:toilet',
  [OmtPoiSubclass.TollBooth]: 'lucide:badge-dollar-sign',
  [OmtPoiSubclass.Townhall]: 'lucide:landmark',
  [OmtPoiSubclass.Toys]: 'lucide:gamepad-2',
  [OmtPoiSubclass.TrainStationEntrance]: 'lucide:train-front',
  [OmtPoiSubclass.TramStop]: 'lucide:tram-front',
  [OmtPoiSubclass.Translator]: 'lucide:languages',
  [OmtPoiSubclass.TravelAgency]: 'lucide:plane',
  [OmtPoiSubclass.TravelAgent]: 'lucide:plane',
  [OmtPoiSubclass.Tutoring]: 'lucide:graduation-cap',
  [OmtPoiSubclass.Union]: 'lucide:users',
  [OmtPoiSubclass.University]: 'lucide:graduation-cap',
  [OmtPoiSubclass.Veterinary]: 'lucide:cross',
  [OmtPoiSubclass.Video]: 'lucide:film',
  [OmtPoiSubclass.VideoGames]: 'lucide:gamepad-2',
  [OmtPoiSubclass.Viewpoint]: 'lucide:binoculars',
  [OmtPoiSubclass.Volleyball]: 'lucide:trophy',
  [OmtPoiSubclass.WasteBasket]: 'lucide:trash-2',
  [OmtPoiSubclass.Watches]: 'lucide:watch',
  [OmtPoiSubclass.WaterPark]: 'lucide:waves',
  [OmtPoiSubclass.WaterSki]: 'lucide:waves',
  [OmtPoiSubclass.WaterUtility]: 'lucide:droplets',
  [OmtPoiSubclass.Weapons]: 'lucide:shield',
  [OmtPoiSubclass.WebDesign]: 'lucide:monitor',
  [OmtPoiSubclass.WeddingPlanner]: 'lucide:heart',
  [OmtPoiSubclass.Wholesale]: 'lucide:warehouse',
  [OmtPoiSubclass.WildlifePark]: 'lucide:paw-print',
  [OmtPoiSubclass.Wine]: 'lucide:wine',
  [OmtPoiSubclass.WinterSports]: 'lucide:mountain-snow',
  [OmtPoiSubclass.Yoga]: 'lucide:trophy',
  [OmtPoiSubclass.Zoo]: 'lucide:paw-print',
}

const formatOmtSubclassLabel = (value: string) =>
  value
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')

export const OMT_POI_SUBCLASS_METADATA: Record<OmtPoiSubclass, PoiDisplayMetadata> =
  Object.fromEntries(
    Object.values(OmtPoiSubclass).map((value) => [
      value,
      {
        label: formatOmtSubclassLabel(value),
        icon: OMT_POI_SUBCLASS_ICONS[value],
      },
    ]),
  ) as Record<OmtPoiSubclass, PoiDisplayMetadata>

export const getOmtPoiSubclassMetadata = (value?: string): PoiDisplayMetadata | undefined =>
  value && isOmtPoiSubclass(value) ? OMT_POI_SUBCLASS_METADATA[value] : undefined

export const isOmtPoiSubclass = (value: string): value is OmtPoiSubclass =>
  Object.values(OmtPoiSubclass).includes(value as OmtPoiSubclass)
