export type PoiDisplayMetadata = {
  label: string
  icon: string
}

// Documented values from https://wiki.openstreetmap.org/wiki/Key:amenity.
export enum OsmAmenityValue {
  Bar = 'bar',
  Biergarten = 'biergarten',
  Cafe = 'cafe',
  FastFood = 'fast_food',
  FoodCourt = 'food_court',
  IceCream = 'ice_cream',
  Pub = 'pub',
  Restaurant = 'restaurant',
  College = 'college',
  DancingSchool = 'dancing_school',
  DrivingSchool = 'driving_school',
  FirstAidSchool = 'first_aid_school',
  Kindergarten = 'kindergarten',
  LanguageSchool = 'language_school',
  Library = 'library',
  SurfSchool = 'surf_school',
  ToyLibrary = 'toy_library',
  ResearchInstitute = 'research_institute',
  Training = 'training',
  MusicSchool = 'music_school',
  School = 'school',
  TrafficPark = 'traffic_park',
  University = 'university',
  BicycleParking = 'bicycle_parking',
  BicycleRepairStation = 'bicycle_repair_station',
  BicycleRental = 'bicycle_rental',
  BicycleWash = 'bicycle_wash',
  BoatRental = 'boat_rental',
  BoatStorage = 'boat_storage',
  BoatSharing = 'boat_sharing',
  BusStation = 'bus_station',
  CarRental = 'car_rental',
  CarSharing = 'car_sharing',
  CarWash = 'car_wash',
  CompressedAir = 'compressed_air',
  VehicleInspection = 'vehicle_inspection',
  ChargingStation = 'charging_station',
  DriverTraining = 'driver_training',
  FerryTerminal = 'ferry_terminal',
  Fuel = 'fuel',
  GritBin = 'grit_bin',
  MotorcycleParking = 'motorcycle_parking',
  Parking = 'parking',
  ParkingEntrance = 'parking_entrance',
  ParkingSpace = 'parking_space',
  Taxi = 'taxi',
  Weighbridge = 'weighbridge',
  Atm = 'atm',
  PaymentTerminal = 'payment_terminal',
  Bank = 'bank',
  BureauDeChange = 'bureau_de_change',
  MoneyTransfer = 'money_transfer',
  PaymentCentre = 'payment_centre',
  BabyHatch = 'baby_hatch',
  Clinic = 'clinic',
  Dentist = 'dentist',
  Doctors = 'doctors',
  Hospital = 'hospital',
  NursingHome = 'nursing_home',
  Pharmacy = 'pharmacy',
  SocialFacility = 'social_facility',
  Veterinary = 'veterinary',
  ArtsCentre = 'arts_centre',
  Brothel = 'brothel',
  Casino = 'casino',
  Cinema = 'cinema',
  CommunityCentre = 'community_centre',
  ConferenceCentre = 'conference_centre',
  EventsVenue = 'events_venue',
  ExhibitionCentre = 'exhibition_centre',
  Fountain = 'fountain',
  Gambling = 'gambling',
  LoveHotel = 'love_hotel',
  MusicVenue = 'music_venue',
  Nightclub = 'nightclub',
  Planetarium = 'planetarium',
  PublicBookcase = 'public_bookcase',
  SocialCentre = 'social_centre',
  Stage = 'stage',
  Stripclub = 'stripclub',
  Studio = 'studio',
  Swingerclub = 'swingerclub',
  Theatre = 'theatre',
  Courthouse = 'courthouse',
  FireStation = 'fire_station',
  Police = 'police',
  PostBox = 'post_box',
  PostDepot = 'post_depot',
  PostOffice = 'post_office',
  Prison = 'prison',
  RangerStation = 'ranger_station',
  Townhall = 'townhall',
  Bbq = 'bbq',
  Bench = 'bench',
  CheckIn = 'check_in',
  DogToilet = 'dog_toilet',
  DressingRoom = 'dressing_room',
  DrinkingWater = 'drinking_water',
  GiveBox = 'give_box',
  Lounge = 'lounge',
  Mailroom = 'mailroom',
  ParcelLocker = 'parcel_locker',
  Shelter = 'shelter',
  Shower = 'shower',
  Telephone = 'telephone',
  Toilets = 'toilets',
  WaterPoint = 'water_point',
  WateringPlace = 'watering_place',
  SanitaryDumpStation = 'sanitary_dump_station',
  Recycling = 'recycling',
  WasteBasket = 'waste_basket',
  WasteDisposal = 'waste_disposal',
  WasteTransferStation = 'waste_transfer_station',
  AnimalBoarding = 'animal_boarding',
  AnimalBreeding = 'animal_breeding',
  AnimalShelter = 'animal_shelter',
  AnimalTraining = 'animal_training',
  BakingOven = 'baking_oven',
  Clock = 'clock',
  Crematorium = 'crematorium',
  DiveCentre = 'dive_centre',
  FuneralHall = 'funeral_hall',
  GraveYard = 'grave_yard',
  HuntingStand = 'hunting_stand',
  InternetCafe = 'internet_cafe',
  Kitchen = 'kitchen',
  KneippWaterCure = 'kneipp_water_cure',
  Lounger = 'lounger',
  Marketplace = 'marketplace',
  Monastery = 'monastery',
  Mortuary = 'mortuary',
  PhotoBooth = 'photo_booth',
  PlaceOfMourning = 'place_of_mourning',
  PlaceOfWorship = 'place_of_worship',
  PublicBath = 'public_bath',
  PublicBuilding = 'public_building',
  RefugeeSite = 'refugee_site',
  VendingMachine = 'vending_machine',
  Hydrant = 'hydrant',
  UserDefined = 'user_defined',
}

const OSM_AMENITY_ICONS: Record<OsmAmenityValue, string> = {
  [OsmAmenityValue.AnimalBoarding]: 'lucide:paw-print',
  [OsmAmenityValue.AnimalBreeding]: 'lucide:paw-print',
  [OsmAmenityValue.AnimalShelter]: 'lucide:paw-print',
  [OsmAmenityValue.AnimalTraining]: 'lucide:paw-print',
  [OsmAmenityValue.ArtsCentre]: 'lucide:palette',
  [OsmAmenityValue.Atm]: 'lucide:banknote',
  [OsmAmenityValue.BabyHatch]: 'lucide:baby',
  [OsmAmenityValue.BakingOven]: 'lucide:cooking-pot',
  [OsmAmenityValue.Bank]: 'lucide:landmark',
  [OsmAmenityValue.Bar]: 'lucide:beer',
  [OsmAmenityValue.Bbq]: 'lucide:flame-kindling',
  [OsmAmenityValue.Bench]: 'lucide:armchair',
  [OsmAmenityValue.BicycleParking]: 'lucide:bike',
  [OsmAmenityValue.BicycleRental]: 'lucide:bike',
  [OsmAmenityValue.BicycleRepairStation]: 'lucide:wrench',
  [OsmAmenityValue.BicycleWash]: 'lucide:droplets',
  [OsmAmenityValue.Biergarten]: 'lucide:beer',
  [OsmAmenityValue.BoatRental]: 'lucide:ship',
  [OsmAmenityValue.BoatSharing]: 'lucide:ship',
  [OsmAmenityValue.BoatStorage]: 'lucide:ship',
  [OsmAmenityValue.Brothel]: 'lucide:building-2',
  [OsmAmenityValue.BureauDeChange]: 'lucide:landmark',
  [OsmAmenityValue.BusStation]: 'lucide:bus',
  [OsmAmenityValue.Cafe]: 'lucide:coffee',
  [OsmAmenityValue.CarRental]: 'lucide:car',
  [OsmAmenityValue.CarSharing]: 'lucide:car',
  [OsmAmenityValue.CarWash]: 'lucide:car',
  [OsmAmenityValue.Casino]: 'lucide:dices',
  [OsmAmenityValue.ChargingStation]: 'lucide:battery-charging',
  [OsmAmenityValue.CheckIn]: 'lucide:badge-check',
  [OsmAmenityValue.Cinema]: 'lucide:film',
  [OsmAmenityValue.Clinic]: 'lucide:cross',
  [OsmAmenityValue.Clock]: 'lucide:clock',
  [OsmAmenityValue.College]: 'lucide:graduation-cap',
  [OsmAmenityValue.CommunityCentre]: 'lucide:building-2',
  [OsmAmenityValue.CompressedAir]: 'lucide:gauge',
  [OsmAmenityValue.ConferenceCentre]: 'lucide:building-2',
  [OsmAmenityValue.Courthouse]: 'lucide:scale',
  [OsmAmenityValue.Crematorium]: 'lucide:flame',
  [OsmAmenityValue.Dentist]: 'lucide:cross',
  [OsmAmenityValue.DiveCentre]: 'lucide:waves',
  [OsmAmenityValue.DogToilet]: 'lucide:paw-print',
  [OsmAmenityValue.Doctors]: 'lucide:stethoscope',
  [OsmAmenityValue.DressingRoom]: 'lucide:shirt',
  [OsmAmenityValue.DrinkingWater]: 'lucide:droplets',
  [OsmAmenityValue.DancingSchool]: 'lucide:music',
  [OsmAmenityValue.DrivingSchool]: 'lucide:car',
  [OsmAmenityValue.DriverTraining]: 'lucide:car',
  [OsmAmenityValue.EventsVenue]: 'lucide:calendar-days',
  [OsmAmenityValue.ExhibitionCentre]: 'lucide:images',
  [OsmAmenityValue.FastFood]: 'lucide:hamburger',
  [OsmAmenityValue.FerryTerminal]: 'lucide:ship',
  [OsmAmenityValue.FireStation]: 'lucide:flame',
  [OsmAmenityValue.FirstAidSchool]: 'lucide:cross',
  [OsmAmenityValue.FoodCourt]: 'lucide:utensils',
  [OsmAmenityValue.Fountain]: 'lucide:waves',
  [OsmAmenityValue.FuneralHall]: 'lucide:building-2',
  [OsmAmenityValue.Gambling]: 'lucide:dices',
  [OsmAmenityValue.GiveBox]: 'lucide:package-open',
  [OsmAmenityValue.GraveYard]: 'lucide:landmark',
  [OsmAmenityValue.GritBin]: 'lucide:box',
  [OsmAmenityValue.Fuel]: 'lucide:fuel',
  [OsmAmenityValue.Hydrant]: 'lucide:flame',
  [OsmAmenityValue.Hospital]: 'lucide:hospital',
  [OsmAmenityValue.HuntingStand]: 'lucide:binoculars',
  [OsmAmenityValue.IceCream]: 'lucide:ice-cream-bowl',
  [OsmAmenityValue.InternetCafe]: 'lucide:wifi',
  [OsmAmenityValue.Kitchen]: 'lucide:cooking-pot',
  [OsmAmenityValue.Kindergarten]: 'lucide:baby',
  [OsmAmenityValue.KneippWaterCure]: 'lucide:droplets',
  [OsmAmenityValue.LanguageSchool]: 'lucide:languages',
  [OsmAmenityValue.Library]: 'lucide:book-open',
  [OsmAmenityValue.Lounge]: 'lucide:armchair',
  [OsmAmenityValue.Lounger]: 'lucide:armchair',
  [OsmAmenityValue.LoveHotel]: 'lucide:heart',
  [OsmAmenityValue.Mailroom]: 'lucide:mail',
  [OsmAmenityValue.Marketplace]: 'lucide:store',
  [OsmAmenityValue.MoneyTransfer]: 'lucide:credit-card',
  [OsmAmenityValue.Monastery]: 'lucide:church',
  [OsmAmenityValue.Mortuary]: 'lucide:building-2',
  [OsmAmenityValue.MotorcycleParking]: 'lucide:bike',
  [OsmAmenityValue.MusicSchool]: 'lucide:music',
  [OsmAmenityValue.MusicVenue]: 'lucide:music',
  [OsmAmenityValue.Nightclub]: 'lucide:music',
  [OsmAmenityValue.NursingHome]: 'lucide:heart-pulse',
  [OsmAmenityValue.Parking]: 'lucide:square-parking',
  [OsmAmenityValue.ParkingEntrance]: 'lucide:square-parking',
  [OsmAmenityValue.ParkingSpace]: 'lucide:square-parking',
  [OsmAmenityValue.ParcelLocker]: 'lucide:package',
  [OsmAmenityValue.PaymentCentre]: 'lucide:credit-card',
  [OsmAmenityValue.PaymentTerminal]: 'lucide:credit-card',
  [OsmAmenityValue.Pharmacy]: 'lucide:pill',
  [OsmAmenityValue.PhotoBooth]: 'lucide:camera',
  [OsmAmenityValue.PlaceOfMourning]: 'lucide:building-2',
  [OsmAmenityValue.PlaceOfWorship]: 'lucide:church',
  [OsmAmenityValue.Planetarium]: 'lucide:telescope',
  [OsmAmenityValue.Police]: 'lucide:shield',
  [OsmAmenityValue.PostBox]: 'lucide:mailbox',
  [OsmAmenityValue.PostDepot]: 'lucide:mail',
  [OsmAmenityValue.PostOffice]: 'lucide:mail',
  [OsmAmenityValue.Prison]: 'lucide:lock',
  [OsmAmenityValue.PublicBath]: 'lucide:waves',
  [OsmAmenityValue.PublicBookcase]: 'lucide:book-open',
  [OsmAmenityValue.PublicBuilding]: 'lucide:building-2',
  [OsmAmenityValue.Pub]: 'lucide:beer',
  [OsmAmenityValue.RangerStation]: 'lucide:trees',
  [OsmAmenityValue.RefugeeSite]: 'lucide:tent',
  [OsmAmenityValue.Recycling]: 'lucide:recycle',
  [OsmAmenityValue.ResearchInstitute]: 'lucide:microscope',
  [OsmAmenityValue.Restaurant]: 'lucide:utensils',
  [OsmAmenityValue.SanitaryDumpStation]: 'lucide:trash',
  [OsmAmenityValue.School]: 'lucide:school',
  [OsmAmenityValue.Shelter]: 'lucide:tent',
  [OsmAmenityValue.Shower]: 'lucide:shower-head',
  [OsmAmenityValue.SocialCentre]: 'lucide:users',
  [OsmAmenityValue.SocialFacility]: 'lucide:heart-handshake',
  [OsmAmenityValue.Stage]: 'lucide:mic-2',
  [OsmAmenityValue.Stripclub]: 'lucide:building-2',
  [OsmAmenityValue.Studio]: 'lucide:mic',
  [OsmAmenityValue.SurfSchool]: 'lucide:waves',
  [OsmAmenityValue.Swingerclub]: 'lucide:building-2',
  [OsmAmenityValue.Taxi]: 'lucide:car-taxi-front',
  [OsmAmenityValue.Telephone]: 'lucide:phone',
  [OsmAmenityValue.Theatre]: 'lucide:theater',
  [OsmAmenityValue.Toilets]: 'lucide:toilet',
  [OsmAmenityValue.Townhall]: 'lucide:landmark',
  [OsmAmenityValue.ToyLibrary]: 'lucide:gamepad-2',
  [OsmAmenityValue.TrafficPark]: 'lucide:traffic-cone',
  [OsmAmenityValue.Training]: 'lucide:graduation-cap',
  [OsmAmenityValue.University]: 'lucide:graduation-cap',
  [OsmAmenityValue.UserDefined]: 'lucide:map-pin',
  [OsmAmenityValue.VehicleInspection]: 'lucide:car',
  [OsmAmenityValue.VendingMachine]: 'lucide:shopping-bag',
  [OsmAmenityValue.Veterinary]: 'lucide:cross',
  [OsmAmenityValue.WasteTransferStation]: 'lucide:trash-2',
  [OsmAmenityValue.WasteBasket]: 'lucide:trash-2',
  [OsmAmenityValue.WasteDisposal]: 'lucide:trash',
  [OsmAmenityValue.WaterPoint]: 'lucide:droplets',
  [OsmAmenityValue.WateringPlace]: 'lucide:droplets',
  [OsmAmenityValue.Weighbridge]: 'lucide:scale',
}

const formatOsmValueLabel = (value: string) =>
  value
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')

export const OSM_AMENITY_METADATA: Record<OsmAmenityValue, PoiDisplayMetadata> = Object.fromEntries(
  Object.values(OsmAmenityValue).map((value) => [
    value,
    {
      label: formatOsmValueLabel(value),
      icon: OSM_AMENITY_ICONS[value],
    },
  ]),
) as Record<OsmAmenityValue, PoiDisplayMetadata>

export const isOsmAmenityValue = (value: string): value is OsmAmenityValue =>
  Object.values(OsmAmenityValue).includes(value as OsmAmenityValue)

