services:
  dnsmasq:
    build:
      context: ./services/dnsmasq
      dockerfile: Dockerfile

    restart: unless-stopped

    command:
      - "--keep-in-foreground"
      - "--log-facility=-"
      - "--log-queries"
      - "--no-resolv"
      - "--server=${LOCAL_DNS_UPSTREAM:-1.1.1.1}"
      - "--server=${LOCAL_DNS_UPSTREAM_SECONDARY:-9.9.9.9}"
      - "--address=/${ROOT_DOMAIN}/${LOCAL_SERVER_IP}"

    ports:
      - "53:53/tcp"
      - "53:53/udp"

    networks:
      - traefik_public

  traefik:
    command:
      - "--api.insecure=true"
      - "--providers.file.filename=/etc/traefik/local.dynamic.yaml"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"

    configs:
      - source: traefik_dynamic_local
        target: /etc/traefik/local.dynamic.yaml

    environment:
      ROOT_DOMAIN: ${ROOT_DOMAIN}

    ports:
      - "80:80"
      - "8081:8080"

  postgres_osm:
    ports:
      - "5433:5432"

    networks:
      - postgres_private
      - traefik_public

  static_tile_server:
    volumes:
      - ./services/static_tile_server/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro

configs:
  traefik_dynamic_local:
    file: ./services/traefik/local.dynamic.yaml
