run target *up_args:
    @just _exec-{{target}} up {{up_args}}

run-job target job_name *run_args:
    @just _exec-{{target}} -f compose.jobs.yaml run --rm {{run_args}} {{job_name}}

exec target +compose_args:
    @just _exec-{{target}} {{compose_args}}

_exec-local +compose_args:
    docker compose --env-file .env --env-file .local.env -f compose.yaml -f compose.local.yaml {{compose_args}}

_exec-prod-mono +compose_args:
    docker compose --env-file .env --env-file .prod.mono.env -f compose.yaml -f compose.prod.mono.yaml {{compose_args}}
