server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;

    location /raster/sen2/ {
        try_files $uri =404;
    }

    location /roads/ {
        try_files $uri =404;
    }

    location /gtfs/ {
        try_files $uri =404;
    }
}
